export const data = [{
    odometer: "200",
    gas: "5",
    gasType: "regular",
    price: "100",
    totalCost: "500",
    date: new Date(),
    time: new Date(),
  },
  {
    odometer: "100",
    gas: "20",
    gasType: "regular",
    price: "95",
    totalCost: "2000",
    date: new Date(),
    time: new Date(),
  },
  {
    odometer: "40",
    gas: "50",
    gasType: "regular",
    price: "90",
    totalCost: "5000",
    date: new Date(),
    time: new Date(),
  },
  {
    odometer: "0",
    gas: "10",
    gasType: "regular",
    price: "70",
    totalCost: "800",
    date: new Date(),
    time: new Date(),
  }]